### ISSUE TITLE
Can't install custom color icon theme

### ISSUE THREAD

**Issue by dpalacio** [sonakinci41/DamaDamas-icon-theme#6]
On current master branch, installation of a custom color settings theme fails with the following error in the included log.
```
# git show --stat
commit 8fb0894f3377d0753b023ca887e26a0c3872d8f9
Author: sonakinci41 <sonakinci41@gmail.com>
Date:   Sun Nov 26 11:44:57 2017 +0300

    add new icons

```

```
# python3 damadamas-installer.py           
Welcome to the DamaDamas icon theme installer.


Damadamas icon theme installer will run as root.
The icon will be installed in /usr/share/icons file.


If you continue the DamaDamas icon theme board will be deleted and installed on your system.
Would you like to do it?(Y) or (N)Y
Damadamas icons are prepared in SVG format.
This advantage gives you the possibility to determine the color of the icons.
 Do you want to change colors? (Y) or (N)::Y
Copying files. Please wait...
/tmp/DamaDamas-icon-theme/mimetypes
/tmp/DamaDamas-icon-theme/devices
/tmp/DamaDamas-icon-theme/status
/tmp/DamaDamas-icon-theme/extras
/tmp/DamaDamas-icon-theme/LICENSE
/tmp/DamaDamas-icon-theme/actions
/tmp/DamaDamas-icon-theme/categories
/tmp/DamaDamas-icon-theme/CMakeLists.txt
/tmp/DamaDamas-icon-theme/index.theme
/tmp/DamaDamas-icon-theme/emblems
/tmp/DamaDamas-icon-theme/README.md
/tmp/DamaDamas-icon-theme/.git
/tmp/DamaDamas-icon-theme/places
/tmp/DamaDamas-icon-theme/apps
Complate.
=====================================

Please specify a file color. 
 Options:
[ ] default 
[ ] black
[ ] blue
[ ] brown
[ ] cyan
[ ] green
[ ] grey
[ ] orange
[ ] pink
[ ] red
[ ] custom
::black

Please select colors for actions icons.
 Options:
[ ] dark
[ ] light
[ ] custom
::dark

Please select colors for panel icons.
 Options:
[ ] dark
[ ] light
[ ] custom
::dark
Change folder colors...
Change actions colors...
Traceback (most recent call last):
  File "damadamas-installer.py", line 190, in <module>
    sarkiKlasorAktar(url + "/DamaDamas-icon-theme/status/panel/","f7f7f7",panel_rengi)
  File "damadamas-installer.py", line 27, in sarkiKlasorAktar
    okunan = dosya.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5155: ordinal not in range(128)
```

**Comment by sonakinci41** [comment]
Thanks for issue,
Unfortunately the error did not come up on my computers.
If you share your distro name, I'm delighted.
36a7161802c320e0f2d4f04c669d71a58849791e I modified the "except" block so that maybe the error is from a single file. I'm glad you're back.(Translate)
